import jemma

test = jemma.jemma("!eli5 discrete mathematics")
test1 = jemma.jemma("!desc discrete mathematics")
test2 = jemma.jemma("!sum discrete mathematics")
test3 = jemma.jemma("!rel discrete mathematics")
test4 = jemma.jemma("!wiki discrete mathematics")
# test.decision()
# test1.decision()
test4.decision()
# test.decision()
# test.decision(test.req_type, test.req_concept)
# print(test.response)
# print(test.req_type)
# print(test.req_concept)
# print(type(test.req_type))
# print(type(test.req_concept))
# print(test.req_type.group())
# print(print(test.req_type.group()))
# print(test.response.text)
# print(test1.response.text)
# print(test2.response.text)
print(test4.response)
print("hello!!")
